[package]
name = "sensor-bridge"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.3", features = ["dialog-all", "shell-open", "system-tray", "window-all"] } # Tauri
systemstat = "0.2"    # read sensor values
serialport = "4.2"    # Write to serial port
rayon = "1.7"         # Parallel processing

image = "0.24"        # Image processing
base64 = "0.21"       # Base64 encoding
imageproc = "0.23"    # Image processing
rusttype = "0.9.3"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
