[package]
name = "sensor-bridge"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
sensor-core = { git = "https://github.com/RouHim/sensor-core.git", branch = "main" }
#sensor-core = { path = "../../sensor-core" }
serde = { version = "1.0", features = ["derive"] }      # Serialization
serde_json = "1.0"                                      # De/Serialize to json
rmp-serde = "1.1"                                       # De/Serialize to MessagePack
tauri = { version = "1.3", features = ["dialog-all", "shell-open", "system-tray", "window-all"] } # Tauri
systemstat = "0.2"                                      # read common system sensor values
rayon = "1.7"                                           # Parallel processing
base64 = "0.21"                                         # Base64 encoding
message-io = { version = "0.17", default-features = false, features = ["tcp"] }     # TCPSocket communication
uuid = { version = "1.4.0", features = ["v4"] }         # Generate UUID v4
image = "0.24"                                          # Image processing

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
