[package]
name = "sensor-bridge"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rmp-serde = "1.1"
tauri = { version = "1.4", features = ["dialog-all", "shell-open", "system-tray", "window-all"] } # Tauri
systemstat = "0.2"    # read sensor values
serialport = "4.2"    # Write to serial port
rayon = "1.7"         # Parallel processing
base64 = "0.21"       # Base64 encoding
sensor-core = { path = "../../sensor-core" }
#sensor-core = { git = "https://github.com/RouHim/sensor-core.git", branch = "main" }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
