[package]
name = "sensor-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
# Read sensor values
wmi = "0.11.4"
serde = "1.0.152"
serde_json = "1.0.91"

# Write to serial port
serialport = "4.2.0"

# Utils
rand = "0.8.5"

# GUI
native-windows-gui = "1.0.12"
native-windows-derive = "1.0.3"